name: Batch

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**

    paths:
      - '.github/workflows/batch.yaml'
      - 'hello-world/batch/**'

jobs:
  build:
    name: Test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cd hello-world/batch && ./hello-world.bat
