name: Dockerfile

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**

    paths:
      - '.github/workflows/dockerfile.yaml'
      - 'hello-world/dockerfile/hello-world.dockerfile'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make dockerfile
