name: PowerShell

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**

    paths:
      - '.github/workflows/powershell.yaml'
      - 'hello-world/powershell/**'

jobs:
  build:
    name: Test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make powershell
